name: Deploy to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude 'client' --exclude 'folders' --exclude '.env' --exclude 'node_modules' --exclude '.git'
          path: .
          remote_path: /home/ubuntu/webServer
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USERNAME }}
          remote_key: ${{ secrets.SERVER_PRIVATE_KEY }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/webServer
            # Create .env file on the server
            rm -f .env
            echo "PORT=${{ secrets.PORT }}" >> .env
            echo "DUFFEL_AUTH_TOKEN=${{ secrets.DUFFEL_AUTH_TOKEN }}" >> .env
            # Install dependencies
            npm install
            # Start or restart the application
            pm2 reload all || pm2 start npm -- start
            sudo systemctl restart nginx
